### ISSUE TITLE
Corona Runtime Error

### ISSUE THREAD

**Issue by galahad9** [dmccuskey/Ghost-vs-Monsters---OOP#1]
![runtime error](https://cloud.githubusercontent.com/assets/1190508/6824736/1d692906-d2f5-11e4-8e8b-9c3e6a01adae.png)

**Comment by dmccuskey** [comment]
thanks for letting me know ! that issue is in the boot script, should be fixed in 1.5.1. i have updated the version here in the this repo, so you can either update or get a newer version of dmc_corona_boot.lua.

cheers ! dmc

**Comment by galahad9** [comment]
![same error](https://cloud.githubusercontent.com/assets/1190508/6858662/1e9a80aa-d411-11e4-8fb5-4f3b18cfae25.png)

**Comment by dmccuskey** [comment]
here is another component necessary to make it work:

"""
since you’re on Windows, don’t forget to update the dmc_corona.cfg file to use Windows paths, eg
LUA_PATH:JSON = [ “.\lib\dmc_corona" ]
"""

i knew that i had fixed the issue. i need to get that info into the docs

**Comment by galahad9** [comment]
YES IT WORKS! GREAT STUFF!!!! THANKS A LOT!

2015-03-29 14:23 GMT+02:00 David McCuskey notifications@github.com:

**Comment by dmccuskey** [comment]
fantastic !
